package View;

import Controller.ControllerMeeting;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTable;
import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;

/**
 *
 * @author idnak
 */
public class completedMeeting extends javax.swing.JDialog {

    private ControllerMeeting controllerMeeting;


    public ControllerMeeting getControllerMeeting() {
        return controllerMeeting;
    }


    public void setControllerMeeting(ControllerMeeting controllerMeeting) {
        this.controllerMeeting = controllerMeeting;
        setListener();
    }
    private void setListener(){
        processBtt.addActionListener(controllerMeeting);
        discount.addChangeListener(controllerMeeting);
        
    }


    public JTable getHairCutTable() {
        return hairCutTable;
    }


    public void setHairCutTable(JTable hairCutTable) {
        this.hairCutTable = hairCutTable;
    }


    public JLabel getClient() {
        return client;
    }


    public void setClient(JLabel client) {
        this.client = client;
    }


    public JLabel getLdate() {
        return date;
    }


    public void setLdate(JLabel date) {
        this.date = date;
    }

 
    public JLabel getLdiscount() {
        return ldiscount;
    }


    public void setLdiscount(JLabel ldiscount) {
        this.ldiscount = ldiscount;
    }


    public JLabel getCommend() {
        return commend;
    }


    public void setCommend(JLabel commend) {
        this.commend = commend;
    }


    public JLabel getInvoice() {
        return invoice;
    }


    public void setInvoice(JLabel linvoice) {
        this.invoice = linvoice;
    }


    public JLabel getLtotal() {
        return totalPrice;
    }


    public void setLtotal(JLabel ltotal) {
        this.totalPrice = ltotal;
    }


    public JButton getProcess() {
        return processBtt;
    }


    public void setProcess(JButton process) {
        this.processBtt = process;
    }


    public JTable getServiceTable() {
        return serviceTable;
    }


    public void setServiceTable(JTable servicesobt) {
        this.serviceTable = servicesobt;
    }

    

    public JSlider getDiscount() {
        return discount;
    }


    public void setDiscount(JSlider discount) {
        this.discount = discount;
    }
    
    
    /**
     * Creates new form completedMeeting
     * @param parent
     * @param model
     */
    public completedMeeting(java.awt.Frame parent, boolean model) {
        super(parent, model);
        initComponents();
        setTitle("Complete Meeting");
        setResizable(false);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompleteMeeting = new org.edisoncor.gui.panel.Panel();
        header = new org.edisoncor.gui.panel.Panel();
        center = new javax.swing.JPanel();
        jPanelProcess = new javax.swing.JPanel();
        processBtt = new javax.swing.JButton();
        centerCompleteMeeting = new javax.swing.JPanel();
        invoice = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabelinvoice = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        jLabelService = new javax.swing.JLabel();
        ldiscount = new javax.swing.JLabel();
        jScrollPaneService = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        jLabelClient = new javax.swing.JLabel();
        jLabelHairCut = new javax.swing.JLabel();
        jScrollPaneHairCut = new javax.swing.JScrollPane();
        hairCutTable = new javax.swing.JTable();
        jLabelDiscount = new javax.swing.JLabel();
        discount = new javax.swing.JSlider();
        jLabelDate = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        jLabelTotalPrice = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        commend = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 480));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelCompleteMeeting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/center.png"))); // NOI18N
        panelCompleteMeeting.setMaximumSize(new java.awt.Dimension(464, 422));
        panelCompleteMeeting.setMinimumSize(new java.awt.Dimension(452, 497));
        panelCompleteMeeting.setPreferredSize(new Dimension(600, 500));
        panelCompleteMeeting.setLayout(new java.awt.BorderLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/header/Meeting.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(464, 75));
        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(464, 75));
        header.setLayout(new java.awt.BorderLayout());
        panelCompleteMeeting.add(header, java.awt.BorderLayout.NORTH);

        center.setOpaque(false);
        center.setLayout(new java.awt.BorderLayout());

        jPanelProcess.setOpaque(false);
        jPanelProcess.setPreferredSize(new java.awt.Dimension(448, 30));
        jPanelProcess.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        processBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/process.png"))); // NOI18N
        processBtt.setBorderPainted(false);
        processBtt.setContentAreaFilled(false);
        processBtt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        processBtt.setFocusPainted(false);
        processBtt.setMinimumSize(new java.awt.Dimension(150, 30));
        processBtt.setPreferredSize(new java.awt.Dimension(150, 30));
        processBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });
        jPanelProcess.add(processBtt);

        center.add(jPanelProcess, java.awt.BorderLayout.SOUTH);

        centerCompleteMeeting.setBackground(new java.awt.Color(214, 209, 209));
        centerCompleteMeeting.setPreferredSize(new java.awt.Dimension(440, 0));

        invoice.setFont(new Font("Serif", Font.BOLD | Font.ITALIC, 20)); // NOI18N
        invoice.setForeground(new java.awt.Color(0, 0, 0));

        date.setFont(new Font("Serif", Font.BOLD | Font.ITALIC, 20)); // NOI18N
        date.setForeground(new java.awt.Color(0, 0, 0));

        jLabelinvoice.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelinvoice.setForeground(new java.awt.Color(0, 0, 0));
        jLabelinvoice.setText("Invoice:");

        client.setFont(new Font("Serif", Font.BOLD | Font.ITALIC, 20)); // NOI18N
        client.setForeground(new java.awt.Color(0, 0, 0));

        jLabelService.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelService.setForeground(new java.awt.Color(0, 0, 0));
        jLabelService.setText("Services obtained");

        ldiscount.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        ldiscount.setForeground(new java.awt.Color(0, 0, 0));

        serviceTable.setFont(new Font("Serif", Font.ITALIC, 20)); // NOI18N
        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Service", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneService.setViewportView(serviceTable);

        jLabelClient.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelClient.setForeground(new java.awt.Color(0, 0, 0));
        jLabelClient.setText("Client:");

        jLabelHairCut.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelHairCut.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHairCut.setText("Haircut");

        hairCutTable.setFont(new Font("Serif", Font.ITALIC, 20)); // NOI18N
        hairCutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Style", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneHairCut.setViewportView(hairCutTable);

        jLabelDiscount.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelDiscount.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDiscount.setText("Discount");

        discount.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        discount.setForeground(new java.awt.Color(0, 0, 0));
        discount.setMajorTickSpacing(5);
        discount.setPaintLabels(true);
        discount.setPaintTicks(true);
        discount.setSnapToTicks(true);
        discount.setValue(0);
        discount.setOpaque(false);

        jLabelDate.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDate.setText("Date:");

        totalPrice.setFont(new Font("Serif", Font.BOLD | Font.ITALIC, 20)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(0, 0, 0));

        jLabelTotalPrice.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabelTotalPrice.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTotalPrice.setText("Total to pay:");

        javax.swing.GroupLayout gl_centerCompleteMeeting = new javax.swing.GroupLayout(centerCompleteMeeting);
        gl_centerCompleteMeeting.setHorizontalGroup(
        	gl_centerCompleteMeeting.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        			.addGap(20)
        			.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        					.addComponent(jLabelinvoice, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        					.addGap(10)
        					.addComponent(invoice, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        					.addGap(43)
        					.addComponent(jLabelDate, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(date, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        					.addComponent(jLabelClient, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        					.addGap(10)
        					.addComponent(client, GroupLayout.PREFERRED_SIZE, 330, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jLabelService, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelHairCut, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        					.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        							.addComponent(jLabelTotalPrice, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(totalPrice, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        							.addComponent(jLabelDiscount, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(discount, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(ldiscount, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(jScrollPaneHairCut, Alignment.LEADING)
        					.addComponent(jScrollPaneService, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        gl_centerCompleteMeeting.setVerticalGroup(
        	gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_centerCompleteMeeting.createSequentialGroup()
        			.addGap(10)
        			.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelDate, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(date, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(invoice, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelinvoice, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addGap(10)
        			.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelClient, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(client, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addGap(10)
        			.addComponent(jLabelService, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPaneService, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabelHairCut, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPaneHairCut, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING)
        				.addComponent(discount, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        				.addComponent(ldiscount, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        				.addComponent(jLabelDiscount, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_centerCompleteMeeting.createParallelGroup(Alignment.LEADING)
        				.addComponent(totalPrice, GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        				.addComponent(jLabelTotalPrice, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(28))
        );
        centerCompleteMeeting.setLayout(gl_centerCompleteMeeting);

        center.add(centerCompleteMeeting, java.awt.BorderLayout.CENTER);

        panelCompleteMeeting.add(center, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 102, 255));
        footer.setOpaque(false);
        footer.setPreferredSize(new java.awt.Dimension(0, 30));
        footer.setLayout(new java.awt.BorderLayout());

        commend.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        commend.setForeground(new java.awt.Color(0, 0, 0));
        footer.add(commend, java.awt.BorderLayout.CENTER);

        panelCompleteMeeting.add(footer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelCompleteMeeting, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed

    }//GEN-LAST:event_processActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.Panel panelCompleteMeeting;
    private javax.swing.JPanel centerCompleteMeeting;
    private javax.swing.JPanel center;
    private javax.swing.JSlider discount;
    private javax.swing.JPanel footer;
    private javax.swing.JTable hairCutTable;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JLabel jLabelTotalPrice;
    private javax.swing.JLabel jLabelinvoice;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JLabel jLabelHairCut;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JPanel jPanelProcess;
    private javax.swing.JScrollPane jScrollPaneService;
    private javax.swing.JScrollPane jScrollPaneHairCut;
    private javax.swing.JLabel client;
    private javax.swing.JLabel date;
    private javax.swing.JLabel ldiscount;
    private javax.swing.JLabel commend;
    private javax.swing.JLabel invoice;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JButton processBtt;
    private javax.swing.JTable serviceTable;
}
